# Data Analysis

## Load Data

In [19]:
import pandas as pd

### Load Life Expectancy

This data was pretty easy to export. The following linken provides downloadable csv files:  http://apps.who.int/gho/data/node.main.688?lang=en

In [20]:
df_life_exp = pd.read_csv('./data/life_exp.csv')
display(df_life_exp.head(5))

,Unnamed: 0,Unnamed: 1,Life expectancy at birth (years),Life expectancy at birth (years).1,Life expectancy at birth (years).2,Life expectancy at age 60 (years),Life expectancy at age 60 (years).1,Life expectancy at age 60 (years).2,Healthy life expectancy (HALE) at birth (years),Healthy life expectancy (HALE) at birth (years).1,Healthy life expectancy (HALE) at birth (years).2,Healthy life expectancy (HALE) at age 60 (years),Healthy life expectancy (HALE) at age 60 (years).1,Healthy life expectancy (HALE) at age 60 (years).2
0,WHO region,Year,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female,Both sexes,Male,Female
1,Africa,2016,61.2,59.6,62.7,16.6,15.9,17.3,53.8,52.6,54.9,12.5,12.0,13.1
2,Africa,2015,60.7,59.1,62.2,16.6,15.8,17.3,53.3,52.1,54.4,12.4,11.8,13.0
3,Africa,2010,57.6,56.4,58.8,16.1,15.4,16.7,50.4,49.6,51.3,12.0,11.5,12.4
4,Africa,2005,53.4,52.3,54.4,15.4,14.7,16.1,46.7,46.0,47.4,11.4,10.9,11.8

### Load Current health expenditure 

This data was pretty easy to export. The following linken provides downloadable csv files: http://apps.who.int/gho/data/node.main.GHEDCHEpcUSSHA2011?lang=en

In [21]:
df_health_expenditure = pd.read_csv('./data/GHED_CHE_pc_US_SHA2011.csv')
display(df_health_expenditure.head(5))

,Unnamed: 0,Current health expenditure (CHE) per capita in US$,Current health expenditure (CHE) per capita in US$.1,Current health expenditure (CHE) per capita in US$.2,Current health expenditure (CHE) per capita in US$.3,Current health expenditure (CHE) per capita in US$.4,Current health expenditure (CHE) per capita in US$.5,Current health expenditure (CHE) per capita in US$.6,Current health expenditure (CHE) per capita in US$.7,Current health expenditure (CHE) per capita in US$.8,Current health expenditure (CHE) per capita in US$.9,Current health expenditure (CHE) per capita in US$.10,Current health expenditure (CHE) per capita in US$.11,Current health expenditure (CHE) per capita in US$.12,Current health expenditure (CHE) per capita in US$.13,Current health expenditure (CHE) per capita in US$.14,Current health expenditure (CHE) per capita in US$.15
0,Country,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
1,Afghanistan,60.1,60.1,56.0,52.2,51.6,45.6,42.3,38.7,31.8,28.4,24.4,20.9,17.5,16.2,No data,No data
2,Albania,265.9,314.9,277.7,247.3,248.2,204.2,207.4,240.4,216.4,172.8,165.9,152.0,113.6,89.9,81.9,75.5
3,Algeria,291.6,357.9,330.2,333.9,286.2,228.4,207.3,206.1,150.4,116.2,100.3,92.1,75.4,66.2,66.5,61.3
4,Andorra,4315.7,5088.2,5751.4,4641.6,4860.5,4595.7,4721.9,4985.6,4764.9,4249.2,4036.8,3539.7,3008.3,2332.2,2081.3,2050.6

### Load World by Income 

The world bank provides sofisticated online tools to collect the data you are interested in. 
Still I didn't found a way to export the data by Income-Level per country in a nice formart
http://datatopics.worldbank.org/world-development-indicators/the-world-by-income-and-region.html
If we wanna download the data from this link it throws an error. 

The Income-Level is defineded based on the GNI (Gross National Income) and the income group threshold is determined as descibred here. https://datahelpdesk.worldbank.org/knowledgebase/articles/378833-how-are-the-income-group-thresholds-determined
We are downloading all the country GNI data [here](https://data.worldbank.org/indicator/NY.GNP.PCAP.CD?end=2017&locations=XM-AF-ET&start=2017&view=map). 
__The levels (high, low e.g) provided in the country data are not the threshold levels as defined here!__ https://datahelpdesk.worldbank.org/knowledgebase/articles/906519 


__Since we didn't find the threshold values in the data bank, we extract the data from the Excel files found here:__
https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups

In [31]:
df_world_income = pd.read_csv('./data/OGHIST.csv', sep=';')
display(df_world_income)

,Unnamed: 0,Bank's fiscal year:,FY89,FY90,FY91,FY92,FY93,FY94,FY95,FY96,...,FY10,FY11,FY12,FY13,FY14,FY15,FY16,FY17,FY18,FY19
0,NaN,Data for calendar year :,1987,1988,1989,1990,1991,1992,1993,1994,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
1,NaN,Low income (L),<= 480,<= 545,<= 580,<= 610,<= 635,<= 675,<= 695,<= 725,...,<= 975,<= 995,"<= 1,005","<= 1,025","<= 1,035","<= 1,045","<= 1,045","<= 1,025","<= 1,005",<= 995
2,NaN,Lower middle income (LM),"481-1,940","546-2,200","581-2,335","611-2,465","636-2,555","676-2,695","696-2,785","726-2,895",...,"976-3,855","996-3,945","1,006-3,975","1,026-4,035","1,036-4,085","1,046-4,125","1,046-4,125","1,026-4,035","1,006-3,955","996-3,895"
3,NaN,Upper middle income (UM),"1,941-6,000","2,201-6,000","2,336-6,000","2,466-7,620","2,556-7,910","2,696-8,355","2,786-8,625","2,896-8,955",...,"3,856-11,905","3,946-12,195","3,976-12,275","4,036-12,475","4,086-12,615","4,126-12,745","4,126-12,735","4,036-12,475","3,956-12,235","3,896-12,055"
4,NaN,High income (H),"> 6,000","> 6,000","> 6,000","> 7,620","> 7,910","> 8,355","> 8,625","> 8,955",...,"> 11,905","> 12,195","> 12,275","> 12,475","> 12,615","> 12,745","> 12,735","> 12,475","> 12,235","> 12,055"
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,AFG,Afghanistan,L,L,L,L,L,L,L,L,...,L,L,L,L,L,L,L,L,L,L
7,ALB,Albania,..,..,..,LM,LM,LM,L,L,...,LM,UM,UM,LM,UM,UM,UM,UM,UM,UM
8,DZA,Algeria,UM,UM,LM,LM,LM,LM,LM,LM,...,UM,UM,UM,UM,UM,UM,UM,UM,UM,UM
9,ASM,American Samoa,H,H,H,UM,UM,UM,UM,UM,...,UM,UM,UM,UM,UM,UM,UM,UM,UM,UM
10,AND,Andorra,..,..,..,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
11,AGO,Angola,..,LM,LM,LM,LM,LM,LM,LM,...,LM,LM,LM,UM,UM,UM,UM,UM,LM,LM
12,ATG,Antigua and Barbuda,UM,UM,UM,UM,UM,UM,UM,UM,...,H,UM,UM,UM,H,H,H,H,H,H
13,ARG,Argentina,UM,UM,LM,LM,UM,UM,UM,UM,...,UM,UM,UM,UM,UM,UM,H,UM,UM,H
14,ARM,Armenia,..,..,..,..,LM,LM,L,L,...,LM,LM,LM,LM,LM,LM,LM,LM,LM,UM
15,ABW,Aruba,H,H,H,H,UM,UM,UM,H,...,H,H,H,H,H,H,H,H,H,H
16,AUS,Australia,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
17,AUT,Austria,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
18,AZE,Azerbaijan,..,..,..,..,LM,LM,LM,L,...,LM,UM,UM,UM,UM,UM,UM,UM,UM,UM
19,BHS,"Bahamas, The",H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
20,BHR,Bahrain,H,H,H,UM,UM,UM,UM,UM,...,H,H,H,H,H,H,H,H,H,H
21,BGD,Bangladesh,L,L,L,L,L,L,L,L,...,L,L,L,L,L,L,LM,LM,LM,LM
22,BRB,Barbados,UM,UM,H,UM,UM,UM,UM,UM,...,H,H,H,H,H,H,H,H,H,H
23,BLR,Belarus,..,..,..,..,UM,UM,UM,LM,...,UM,UM,UM,UM,UM,UM,UM,UM,UM,UM
24,BEL,Belgium,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
25,BLZ,Belize,LM,LM,LM,LM,LM,LM,LM,LM,...,LM,LM,LM,LM,UM,UM,UM,UM,UM,UM
26,BEN,Benin,L,L,L,L,L,L,L,L,...,L,L,L,L,L,L,L,L,L,L
27,BMU,Bermuda,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
28,BTN,Bhutan,L,L,L,L,L,L,L,L,...,LM,LM,LM,LM,LM,LM,LM,LM,LM,LM
29,BOL,Bolivia,LM,LM,LM,LM,LM,LM,LM,LM,...,LM,LM,LM,LM,LM,LM,LM,LM,LM,LM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,TTO,Trinidad and Tobago,UM,UM,UM,UM,UM,UM,UM,UM,...,H,H,H,H,H,H,H,H,H,H
204,TUN,Tunisia,LM,LM,LM,LM,LM,LM,LM,LM,...,LM,LM,UM,UM,UM,UM,UM,LM,LM,LM
205,TUR,Turkey,LM,LM,LM,LM,LM,LM,LM,LM,...,UM,UM,UM,UM,UM,UM,UM,UM,UM,UM
206,TKM,Turkmenistan,..,..,..,..,LM,LM,LM,LM,...,LM,LM,LM,UM,UM,UM,UM,UM,UM,UM
207,TCA,Turks and Caicos Islands,..,..,..,..,..,..,..,..,...,..,H,H,H,H,H,H,H,H,H
208,TUV,Tuvalu,..,..,..,..,..,..,..,..,...,..,LM,LM,UM,UM,UM,UM,UM,UM,UM
209,UGA,Uganda,L,L,L,L,L,L,L,L,...,L,L,L,L,L,L,L,L,L,L
210,UKR,Ukraine,..,..,..,..,LM,LM,LM,LM,...,LM,LM,LM,LM,LM,LM,LM,LM,LM,LM
211,ARE,United Arab Emirates,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
212,GBR,United Kingdom,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
213,USA,United States,H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
214,URY,Uruguay,UM,UM,UM,UM,UM,UM,UM,UM,...,UM,UM,UM,UM,H,H,H,H,H,H
215,UZB,Uzbekistan,..,..,..,..,LM,LM,LM,LM,...,L,LM,LM,LM,LM,LM,LM,LM,LM,LM
216,VUT,Vanuatu,LM,LM,LM,LM,LM,LM,LM,LM,...,LM,LM,LM,LM,LM,LM,LM,LM,LM,LM
217,VEN,"Venezuela, RB",UM,UM,UM,UM,UM,UM,UM,LM,...,UM,UM,UM,UM,UM,UM,H,UM,UM,UM
218,VNM,Vietnam,L,L,L,L,L,L,L,L,...,L,LM,LM,LM,LM,LM,LM,LM,LM,LM
219,VIR,Virgin Islands (U.S.),H,H,H,H,H,H,H,H,...,H,H,H,H,H,H,H,H,H,H
220,PSE,West Bank and Gaza,..,..,..,..,..,..,..,LM,...,LM,LM,LM,LM,LM,LM,LM,LM,LM,LM
221,YEM,"Yemen, Rep.",LM*,LM*,LM,LM,L,L,L,L,...,L,LM,LM,LM,LM,LM,LM,LM,LM,L
222,ZMB,Zambia,L,L,L,L,L,L,L,L,...,L,L,LM,LM,LM,LM,LM,LM,LM,LM
223,ZWE,Zimbabwe,LM,LM,LM,LM,L,L,L,L,...,L,L,L,L,L,L,L,L,L,L
224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,CSK,Czechoslovakia (former),..,..,..,UM,UM,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,MYT,Mayotte,..,..,..,H,UM,UM,UM,UM,...,UM,UM,UM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,ANT,Netherlands Antilles (former),UM,UM,UM,UM,UM,UM,UM,H,...,H,H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,YUG,Serbia and Montenegro (former),..,..,..,..,..,LM,LM,LM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
231,SUN,USSR (former),..,..,..,UM,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
232,YUGf,Yugoslavia (former),UM,UM,UM,UM,UM,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Load GDP per capita

This data was pretty easy to export. The following linken provides downloadable csv files: https://databank.worldbank.org/data/reports.aspx?source=2&series=NY.GDP.PCAP.CD&country=#advancedDownloadOptions

In [22]:
df_gpd_per_capita = pd.read_csv('./data/gdp_per_capita.csv')
display(df_gpd_per_capita.head(5))

,Series Name,Series Code,Country Name,Country Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017]
0,GDP per capita (current US$),NY.GDP.PCAP.CD,Afghanistan,AFG,59.777327,59.878153,58.492874,78.782758,82.208444,101.290471,...,373.361116,445.893298,553.300289,603.537023,669.009051,638.612543,629.345250,569.577923,561.778746,585.850064
1,GDP per capita (current US$),NY.GDP.PCAP.CD,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,...,4370.539647,4114.136545,4094.358832,4437.178068,4247.614308,4413.081697,4578.666728,3952.830781,4131.872341,4537.862492
2,GDP per capita (current US$),NY.GDP.PCAP.CD,Algeria,DZA,244.824806,213.485905,171.209809,225.530596,236.610190,248.378144,...,4905.254866,3868.831230,4463.394675,5432.413320,5565.134521,5471.123389,5466.425778,4160.220067,3916.881571,4123.389937
3,GDP per capita (current US$),NY.GDP.PCAP.CD,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,9871.997194,12058.263823,10352.822762,10375.994215,11660.329531,11589.853002,11598.751736,11865.963232,11834.745229,NaN
4,GDP per capita (current US$),NY.GDP.PCAP.CD,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,...,47785.659086,43339.379875,39736.354063,41098.766942,38391.080867,40619.711298,42294.994727,36038.267604,37231.815671,39146.548836

### Load Research and development expenditure

This data was pretty easy to export. The following linken provides downloadable csv files: https://databank.worldbank.org/data/reports.aspx?source=2&series=GB.XPD.RSDV.GD.ZS&country=

In [23]:
df_research_dev_exp = pd.read_csv('./data/research_development_expenditure.csv')
display(df_research_dev_exp.head(5))

,Series Name,Series Code,Country Name,Country Code,1960 [YR1960],1961 [YR1961],1962 [YR1962],1963 [YR1963],1964 [YR1964],1965 [YR1965],...,2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017]
0,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,Albania,ALB,NaN,NaN,NaN,NaN,NaN,NaN,...,0.15421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,Algeria,DZA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,American Samoa,ASM,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,Andorra,AND,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN